# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_NN_2Set_cpp <- function(data, query_data, D, ND, NQ, K, EPS, SEARCHTYPE, USEBDTREE, SQRAD, distances) {
    .Call('_RANNinf_get_NN_2Set_cpp', PACKAGE = 'RANNinf', data, query_data, D, ND, NQ, K, EPS, SEARCHTYPE, USEBDTREE, SQRAD, distances)
}

get_NN_2Set <- function(R_data, R_query_data, R_d, R_nd, R_nq, R_k, R_error_bound, R_searchtype, R_usebdtree, R_sqRad, R_distances, R_verbose) {
    .Call('_RANNinf_get_NN_2Set', PACKAGE = 'RANNinf', R_data, R_query_data, R_d, R_nd, R_nq, R_k, R_error_bound, R_searchtype, R_usebdtree, R_sqRad, R_distances, R_verbose)
}

get_points_in_radius_cpp <- function(data, query_data, D, ND, NQ, K, EPS, USEBDTREE, SQRAD) {
    .Call('_RANNinf_get_points_in_radius_cpp', PACKAGE = 'RANNinf', data, query_data, D, ND, NQ, K, EPS, USEBDTREE, SQRAD)
}

get_points_indices_in_radius_cpp <- function(data, query_data, D, ND, NQ, K, EPS, USEBDTREE, SQRAD) {
    .Call('_RANNinf_get_points_indices_in_radius_cpp', PACKAGE = 'RANNinf', data, query_data, D, ND, NQ, K, EPS, USEBDTREE, SQRAD)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_RANNinf_RcppExport_registerCCallable', PACKAGE = 'RANNinf')
})
